### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by SurgicalSteel** [meisaputri21/Indonesian-Twitter-Emotion-Dataset#1]
First of all, I must say that this is a very interesting and well collected dataset.
However, as I looked down to this raw dataset (1), I found a few phone numbers left uncensored.
I am glad that you have censored usernames and urls, and hoping that you will do the same for phone numbers.
~~Will you consider to censor those phone numbers?~~

Thank you.

1. https://raw.githubusercontent.com/meisaputri21/Indonesian-Twitter-Emotion-Dataset/master/Twitter_Emotion_Dataset.csv

**Comment by meisaputri21** [comment]
Thanks for the suggestion
