### ISSUE TITLE
Indonesian typography dictionary to normalize abbreviation and misspelling in tweets

### ISSUE THREAD

**Issue by rhiosutoyo** [meisaputri21/Indonesian-Twitter-Emotion-Dataset#4]
Hi, thank you for sharing the dataset of Indonesian of Twitter Emotion. I wonder if the team could also share the Indonesian typography dictionary to normalize abbreviation and misspelling in tweets. Thank you.

**Comment by meisaputri21** [comment]
Hi, we have uploaded the abbreviation dictionary into the repository. Thank you.

**Comment by rhiosutoyo** [comment]
Hi. Thank you for the abbreviation dictionary. I really appreciate it. 👍
